FCC-4 fixed all cards expanding on expand
fullstacklabs/toy-blocks-client-angular pull request #16
Opened 2020-12-17 15:43 UTC by matthewsnyderfs

2020-12-18 15:25 UTC, bencarle requested changes
This PR is introducing unrelated style changes that are causing more linter failures.

2020-12-18 15:25 UTC, bencarle commented on src/app/services/nodesStore.service.ts
> +            ...node,
Is the entire node needed here, or just the `url`?

2020-12-18 15:32 UTC, matthewsnyderfs commented on src/app/services/nodesStore.service.ts
> +            ...node,
Technically just the url but being the "nodeStore" I thought it should return nodes. Would you like me to change it to just the url?

2020-12-21 14:32 UTC, bencarle approved these changes

2020-12-21 14:32 UTC, merged